services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - example.env
    depends_on:
      - db
      - redis
      - mailhog
    restart: always

  db:
    image: postgres:15
    restart: always
    env_file:
      - example.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pg_data:
